add Natchez backend that provides a Logger[F] given a Trace[F]
typelevel/log4cats pull request #720
Opened 2023-01-10 18:55 UTC by bpholt

I was looking at the [OpenTelemetry logging spec](https://opentelemetry.io/docs/reference/specification/logs/) the other day and saw this excerpt:

> This is in essence the philosophy behind OpenTelemetry’s logs support. We embrace existing logging solutions and make sure OpenTelemetry works nicely with existing logging libraries … 
> 
> For traces and metrics OpenTelemetry defines a new API that application developers must use to emit traces and metrics.
>
> For logs we did not take the same path. We realized that there is a much bigger and more diverse legacy in logging space. There are many existing logging libraries in different languages, each having their own API. Many programming languages have established standards for using particular logging libraries.

and it occurred to me that it might be nice to use the familiar log4cats `Logger[F]` interface for logging, even in apps that have Natchez `Trace[F]` wired throughout. 

I think this may also provide an easier migration path in an application that has existing `Logger[F]` statements throughout—one may be able to replace a `Logger` constraint with a `Trace` constraint, and then benefit from those existing log statements getting attached to spans going forward. (Eventually many of those logs will prove redundant and be removed.)

2023-01-10 19:10 UTC, armanbilge commented
👍 but this will create a circular dependency with natchez (which currently depends on log4cats). And also it would add an unstable 0.x dependency to log4cats which is in stable 2.x series.

Should we consider moving this either to Natchez repo, or creating a log4cats-natchez repo?

2023-01-10 19:12 UTC, bpholt commented
> this will create a circular dependency with natchez

I think this is only true for the `natchez-log` module, so it might be ok in practice?

2023-01-10 19:16 UTC, armanbilge commented
> I think this is only true for the `natchez-log` module, so it might be ok in practice?

Well, not really. Consider when breaking Scala Native 0.5 comes out, how will we upgrade these repos? Which will release first?

2023-01-10 19:22 UTC, bpholt commented
Oh, I see what you mean—I was thinking about it from a runtime perspective.

Maybe it should be a separate repo so it can be versioned independently from either side? (This isn't the place for the discussion, but I've been thinking that it might be a good idea to split out the Natchez backends generally, so I'm also hesitant to add more over there.)

Who could create a new typelevel repo for this? I'd be happy to set things up there, if someone wants to create the repo and make me the maintainer.

2023-01-10 19:23 UTC, armanbilge commented
> but I've been thinking that it might be a good idea to split out the Natchez backends generally

yup, I think so as well. honestly it needs its own GH org ...

--- 

> Who could create a new typelevel repo for this? I'd be happy to set things up there, if someone wants to create the repo and make me the maintainer.

I can do this, any preference on the name? :)

2023-01-10 19:35 UTC, bpholt commented
> I can do this, any preference on the name? :)

I proposed the module be `log4cats-natchez`, so that works for me.

We probably don't have to decide now, but that name raises some questions about the scope of the repo—e.g. it's not obvious _from the name alone_ that the log4cats backend for Natchez shouldn't belong there too. (I don't really want to tackle that right now, but I'd be open to discussing it if Natchez decides to move backends around)

2023-01-10 19:37 UTC, armanbilge commented
Done: https://github.com/typelevel/log4cats-natchez/

2023-01-10 19:39 UTC, bpholt commented
Great, thank you! I'll move this code over there and update this PR to mention the new backend in the log4cats documentation.

2023-01-10 19:46 UTC, rossabaker requested changes
log4cats needs to have a very conservative strategy for breaking binary compatibility, given its uptake in several other projects.  We can't couple its release cycle to Natchez at its stage of maturity.  This integration could live in a separate repository, even hosted by Typelevel.

For a transparent integration of "legacy" logging and Open Telemetry, I would probably look first to a [log appender](https://opentelemetry.io/docs/reference/specification/logs/api/#how-to-create-log4j-style-appender).  For applications to generate events specifically with Otel in mind, there's an [event specification](https://opentelemetry.io/docs/reference/specification/logs/event-api/) that adds some extra conventional attributes.

2023-01-11 00:15 UTC, bpholt commented
I'm going to close this for now. I'll update the docs with a link to the new repo once it's published!

2023-01-11 00:15 UTC, closed without merging